import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

/* Builds the list of everything the app needs to boot, with a content hash per file, and
   renders it as the classic script the service worker imports.

   Pure apart from reading the files: the generator script writes what this returns, and the
   test regenerates it and compares, so a shipped file that changed without the manifest being
   regenerated is a failing test rather than a stale cache in someone's browser. */

/* Directories walked whole, by extension. Anything not listed is not shipped: tests, scripts,
   docs and the repo's own metadata are not part of what the browser loads. */
const TREES = [
  { dir: 'src/css', extensions: ['.css'] },
  { dir: 'src/js', extensions: ['.js'] },
  { dir: 'icons', extensions: ['.png', '.svg'] }
];

const ROOT_FILES = ['index.html', 'manifest.webmanifest'];

/* The service worker and the file it imports are managed by the browser's own script cache,
   not by us. Precaching them would be a second, staler copy of the thing doing the caching. */
export const NOT_SHIPPED = Object.freeze(['sw.js', 'precache-manifest.js']);

export const PRECACHE_FILE = 'precache-manifest.js';

function walk(root, dir, extensions, found = []) {
  const absolute = join(root, dir);

  for (const name of readdirSync(absolute).sort()) {
    const path = join(absolute, name);

    if (statSync(path).isDirectory()) {
      walk(root, join(dir, name), extensions, found);
    } else if (extensions.some((extension) => name.endsWith(extension))) {
      found.push(relative(root, path).split(sep).join('/'));
    }
  }

  return found;
}

export function shippedFiles(root) {
  const files = [...ROOT_FILES];

  for (const tree of TREES) {
    files.push(...walk(root, tree.dir, tree.extensions));
  }

  return files.filter((file) => !NOT_SHIPPED.includes(file)).sort();
}

export function hashBytes(bytes) {
  return createHash('sha256').update(bytes).digest('hex');
}

/* Taken out of index.html rather than written down again. The integrity attributes pin the
   bytes; this pins the same urls, so a Leaflet version bump cannot leave the worker caching
   the old one. */
export function cdnUrls(root) {
  const html = readFileSync(join(root, 'index.html'), 'utf8');
  const found = html.match(/https:\/\/cdn\.jsdelivr\.net\/[^"']+/g) ?? [];

  return [...new Set(found)].sort();
}

export function buildPrecache(root) {
  const entries = shippedFiles(root).map((file) => ({
    url: file,
    hash: hashBytes(readFileSync(join(root, file)))
  }));

  const remote = cdnUrls(root).map((url) => ({ url, hash: null }));

  /* The version is the hash of the whole list, urls included, so renaming a file changes it
     just as surely as editing one, and so a new CDN pin does too. Twelve hex characters is
     plenty to name a cache with and short enough to read in devtools. */
  const combined = [...entries, ...remote].map((entry) => entry.url + ':' + entry.hash).join('\n');

  return {
    version: hashBytes(combined).slice(0, 12),
    entries,
    remote: remote.map((entry) => entry.url)
  };
}

/* A classic script, because a service worker reads it with importScripts and needs the version
   synchronously to name its cache. Generated, so it says so. */
export function renderPrecache(precache) {
  const lines = [
    '/* Generated by scripts/build-precache.js. Do not edit by hand.',
    '',
    '   Every file the app needs to boot, with the sha-256 of its contents, plus the pinned CDN',
    '   urls. VERSION is the hash of the whole list and names the cache, so any change to any',
    '   shipped file produces a new cache rather than a half-updated old one.',
    '',
    '   tests/pwa/precache.test.js regenerates this and compares, so a file cannot change',
    '   without it. Run npm run precache. */',
    'self.PRECACHE_VERSION = ' + JSON.stringify(precache.version) + ';',
    '',
    'self.PRECACHE_FILES = [',
    ...precache.entries.map(
      (entry, index) =>
        '  { url: ' +
        JSON.stringify(entry.url) +
        ', hash: ' +
        JSON.stringify(entry.hash) +
        ' }' +
        (index === precache.entries.length - 1 ? '' : ',')
    ),
    '];',
    '',
    '/* Pinned exactly as index.html loads them, and fetched in cors mode to match the',
    '   crossorigin attributes there - an opaque response cannot be served back. */',
    'self.PRECACHE_REMOTE = [',
    ...precache.remote.map(
      (url, index) => '  ' + JSON.stringify(url) + (index === precache.remote.length - 1 ? '' : ',')
    ),
    '];',
    ''
  ];

  return lines.join('\n');
}
